# Generated by Django 5.2.7 on 2025-10-30 21:53

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(db_index=True, help_text='Unix timestamp in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feelings', models.TextField(blank=True, help_text='Personal emotional content', null=True)),
                ('project_notes', models.TextField(blank=True, help_text='Project-specific technical notes', null=True)),
                ('technical_insights', models.TextField(blank=True, help_text='General technical learnings', null=True)),
                ('user_context', models.TextField(blank=True, help_text='User interaction observations', null=True)),
                ('world_knowledge', models.TextField(blank=True, help_text='General domain knowledge', null=True)),
                ('content', models.TextField(blank=True, help_text='Simple text content (alternative to sections)', null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_dimensions', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='social.team')),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['team', '-timestamp'], name='social_jour_team_id_9d4b51_idx'), models.Index(fields=['team', '-created_at'], name='social_jour_team_id_dc0c80_idx')],
            },
        ),
    ]
